### ISSUE TITLE
deploy: unable to resolve artefact

### ISSUE THREAD

**Issue by rbaumgar** [jbossdemocentral/rhpam7-install-demo#1]
I installed PAM7 with init-openshift.sh into my minishift.
Server came up without any issue.
But I am not able to deploy the sample project...

14:48:31,046 WARN  [org.appformer.maven.integration.MavenRepository] (default task-40) Unable to resolve artifact: mortgages:mortgages:1.0.0-SNAPSHOT
14:48:31,758 WARN  [org.appformer.maven.integration.MavenRepository] (default task-40) Unable to resolve artifact: mortgages:mortgages:pom:1.0.0-SNAPSHOT
14:48:31,758 ERROR [org.kie.server.services.impl.KieServerImpl] (default task-40) Error creating container 'mortgages_1.0.0-SNAPSHOT' for module 'mortgages:mortgages:1.0.0-SNAPSHOT': java.lang.RuntimeException: Cannot find KieModule: mortgages:mortgages:1.0.0-SNAPSHOT

I tried to import the project via "Try Samples" or via "Import Project" (https://github.com/jbossdemocentral/rhpam7-mortgage-demo-repo)

**Comment by DuncanDoyle** [comment]
Since this issue has been opened, we have moved to 7.0.2.GA of PAM. Would you be able to try this again and see whether you're still experiencing this issue?
