### ISSUE TITLE
GitHub Client (gh) & Desktop: Cloning Failures - Unable to clone main or tag 

### ISSUE THREAD

**Issue by GrooveCS** [jbossdemocentral/rhpam7-install-demo#21]
### Cloning Failure

I have been unable to clone "main" or one of the branches

1. GitHub Client (gh)
1. GitHub Desktop 
1. git bash
1. GitKraken

## Steps to Reproduce

1. Click on the "Clone" button, and the system open GitHub Desktop 
1. The system opens the application and then displays an error message
1. Retry a few times
1. Attempt running the suggestion ``

## Context

Supporting resources

**GitHub Desktop Source**
![image](https://github.com/DiffThink/assests/blob/feature/20201113-Cloning-Failures/media/issues/20201113-github-clone-fail/2020-11-13T0803ESTGitHubDesktopFailed.gif?raw=true)

**GitHub Desktop Fork**
![image](https://github.com/DiffThink/assests/blob/feature/20201113-Cloning-Failures/media/issues/20201113-github-clone-fail/2020-11-13T0804EST.GitHubDesktopFork.gif?raw=true)

![image](https://github.com/DiffThink/assests/blob/feature/20201113-Cloning-Failures/media/issues/20201113-github-clone-fail/2020-11-13T0811EST.GitHubClientFailed.gif?raw=true)

**Error Message GitHub Desktop**
![image](https://user-images.githubusercontent.com/1635152/99104918-a6a0e980-25af-11eb-9aa6-37a438c4af76.png)

**Error Message GitHub Client (gh)**
![image](https://user-images.githubusercontent.com/1635152/99105183-0f886180-25b0-11eb-8ee7-b31a877b7804.png)

#### Operating System
* OS Name   Microsoft Windows 10 Pro for Workstations
* Version   10.0.19041 Build 19041
* Other OS Description  Not Available
* OS Manufacturer   Microsoft Corporation

* System Manufacturer   Acer
* System Model  Aspire TC-865
* System Type   x64-based PC

* Processor Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 2808 Mhz, 6 Core(s), 6 Logical Processor(s)
* BIOS Version/Date American Megatrends Inc R01-A3, 5/16/2018
* SMBIOS Version    3.1
* Embedded Controller Version   170.170
* BIOS Mode UEFI
* BaseBoard Manufacturer    Acer
* BaseBoard Product Aspire TC-865
* BaseBoard Version V:1.1

## Failure Logs

I will retain the log when trying in the future.

**Comment by eschabell** [comment]
Hi, would it have something to do with the path name being too long? How deep are you in the windows file system when running this? I can't test on windows, but that's often an issue...
