### ISSUE TITLE
Readme Link for Business Central 7.0.0.ER2 deployable is Broken

### ISSUE THREAD

**Issue by pacificera** [jbossdemocentral/rhpam7-install-demo#6]
Readme Link is Broken for Red Hat Process Automation Manager: Business Central 7.0.0.ER2 deployable for EE7.  It points to a "coming soon" link on Wikimedia.

**Comment by DuncanDoyle** [comment]
Fixed: https://github.com/jbossdemocentral/rhpam7-install-demo/commit/62115560943eb04e27ccfe459cd31ae49b510a8e
